### ISSUE TITLE
How do I write my own ConditionFragment?

### ISSUE THREAD

**Issue by DanieleMarchei** [fadoss/maude-bindings#1]
I'd like to perform a search with a custom ConditionFragment, something along the line of:
`search term =>* t:MyList such that length(t) < 10`

How can I implement a "LessThan" ConditionFragment? Is it possible to do it in python or do I have to write my own implementation in C++ and rebuild the project?

**Comment by ningit** [comment]
There are no *LessThan* condition fragments in Maude, but a Boolean expression `e` can be used in the interpreter as syntactic sugar for the equality condition fragment `e = true`. Indeed, issuing your command in the interpreter will show something like:

```
Maude> search term =>* t:MyList such that length(t:MyList) < 10 .
search in YOUR-MODULE : term =>* t:MyList such that length(t:MyList) < 10 = true .

Solution 1 (state 0)
```
Hence, you can build the condition fragment as `cf = maude.EqualityCondition(m.parseTerm('length(t:MyList) < 10'), m.parseTerm('true'))`, and then you can search with `term.search(maude.ANY_STEPS, m.parseTerm('t:MyList'), [cf])`.

**Comment by DanieleMarchei** [comment]
I guess I never thought about it, thanks!
