### ISSUE TITLE
How to get meta information of a search 

### ISSUE THREAD

**Issue by ozan-k** [fadoss/maude-bindings#4]
`solutions = myTerm.search(maude.ONE_STEP,target1)`

I have a solutions object as the one above. How can I get the substitutions of each solution here? I could not find this in the documentation. An example would help.

Thanks,
Ozan

**Comment by ningit** [comment]
> How can I get the substitutions of each solution here? 

Iterating over `solutions`.  The iterator returns tuples ([`Term`](https://fadoss.github.io/maude-bindings/#maude.Term), [`Substitution`](https://fadoss.github.io/maude-bindings/#maude.Substitution), function, `int`) with the target, the matching substitution, a function to obtain the path to it, and the number of rewrites.

```python
for term, subs, _, _ in myTerm.search(maude.ONE_STEP,target1):
    # do whatever you want with the substitution subs
```

> I could not find this in the documentation.

The documentation of the return type of the [`search` method](https://fadoss.github.io/maude-bindings/#maude.Term.search) says that it returns a [`RewriteSequenceSearch` object](https://fadoss.github.io/maude-bindings/#maude.RewriteSequenceSearch). Then, the documentation of this latter explains the details of the iterator.

> An example would help.

There are some [here](https://github.com/fadoss/maude-bindings/blob/65dc361dd47ea5a6b7b9f3139dfb5168e425f613/tests/python/test.py#L47).
